config/routes.rb
Rails.application.routes.draw do
  resources :chessboards
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'chessboards#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chessboard.rb
class Chessboard < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chessboards_controller.rb
class ChessboardsController < ApplicationController
  before_action :set_chessboard, only: [:show, :edit, :update, :destroy]

  # GET /chessboards
  # GET /chessboards.json
  def index
    @chessboards = Chessboard.all
  end

  # GET /chessboards/1
  # GET /chessboards/1.json
  def show
  end

  # GET /chessboards/new
  def new
    @chessboard = Chessboard.new
  end

  # GET /chessboards/1/edit
  def edit
  end

  # POST /chessboards
  # POST /chessboards.json
  def create
    @chessboard = Chessboard.new(chessboard_params)

    respond_to do |format|
      if @chessboard.save
        format.html { redirect_to @chessboard, notice: 'Chessboard was successfully created.' }
        format.json { render :show, status: :created, location: @chessboard }
      else
        format.html { render :new }
        format.json { render json: @chessboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chessboards/1
  # PATCH/PUT /chessboards/1.json
  def update
    respond_to do |format|
      if @chessboard.update(chessboard_params)
        format.html { redirect_to @chessboard, notice: 'Chessboard was successfully updated.' }
        format.json { render :show, status: :ok, location: @chessboard }
      else
        format.html { render :edit }
        format.json { render json: @chessboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chessboards/1
  # DELETE /chessboards/1.json
  def destroy
    @chessboard.destroy
    respond_to do |format|
      format.html { redirect_to chessboards_url, notice: 'Chessboard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chessboard
      @chessboard = Chessboard.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chessboard_params
      params.require(:chessboard).permit(:dimension, :theme)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chessboards_helper.rb
module ChessboardsHelper
	X_OFFSET = 115
	Y_OFFSET = 34
	INTERVAL = 33
	INTERVAL = 33
end

app/views/chessboards/_form.html.erb
<%= form_with(model: chessboard, local: true) do |form| %>
  <% if chessboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chessboard.errors.count, "error") %> prohibited this chessboard from being saved:</h2>

      <ul>
      <% chessboard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :dimension %>
    <%= form.number_field :dimension %>
  </div>

  <div class="field">
    <%= form.label :theme %>
    <%= form.text_field :theme %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/chessboards/edit.html.erb
<h1>Editing Chessboard</h1>

<%= render 'form', chessboard: @chessboard %>

<%= link_to 'Show', @chessboard %> |
<%= link_to 'Back', chessboards_path %>

app/views/chessboards/index.html.erb
<!-- 画棋盘 - Draw Chessboard -->
<center>
  <div id='chessboard_container'><%= image_tag 'chess-board.png', size: '675x600', id: 'chessboard'%></div>
</center>


<!-- 谁是当前棋手？黑先白后- Who is current player? -->
<%= hidden_field_tag 'current_player', 'black' %>

<center>
  <span id='white'><%= image_tag 'white-piece.png', size: '60x60'%></span>
  <span id='black'><%= image_tag 'black-piece.png', size: '60x60'%></span>
</center>

<!-- 棋盒里的棋子 chess pieces in bucket -->
<span id='white_piece' style='display: none'><%= image_tag 'white-piece.png', size: '30x30'%></span>
<span id='black_piece' style='display: none'><%= image_tag 'black-piece.png', size: '30x30'%></span>



<script>
  $('#chessboard').bind('click', function(e){
    if(isBlackTurn()){
      chess_piece = pickUpBlack();
      putOnChessboard(chess_piece, e.pageX, e.pageY);
    }else{
      chess_piece = pickUpWhite();
      putOnChessboard(chess_piece, e.pageX, e.pageY);
    }
  });
</script>

app/views/chessboards/new.html.erb
<h1>New Chessboard</h1>

<%= render 'form', chessboard: @chessboard %>

<%= link_to 'Back', chessboards_path %>

app/views/chessboards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dimension:</strong>
  <%= @chessboard.dimension %>
</p>

<p>
  <strong>Theme:</strong>
  <%= @chessboard.theme %>
</p>

<%= link_to 'Edit', edit_chessboard_path(@chessboard) %> |
<%= link_to 'Back', chessboards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Go</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>